repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.39.9
    hooks:
      - id: basedpyright
        additional_dependencies:
          - aioconsole
          - aiohttp
          - aiointercept
          - async-timeout
          - pytest
          - pytest-asyncio
          - pytest-mock
          - websockets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.28.0
    hooks:
      - id: zizmor
